# Generated by Django 4.1.4 on 2023-01-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='SubscribeModel',
        ),
    ]
