# Generated by Django 4.1.4 on 2023-01-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_rename_subscribe_subscribemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribeModel',
            new_name='Subscribe',
        ),
    ]
