# Generated by Django 4.1.4 on 2023-01-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='no_image/product-no-image.jpeg', null=True, upload_to='categories/')),
                ('banner', models.ImageField(blank=True, default='no_image/banner-no-image.jpeg', null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('offer', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
