# Generated by Django 4.1.4 on 2023-01-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='shipping_id',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
