# Generated by Django 4.1.4 on 2023-01-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
        ('cart', '0004_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='discount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
