# Generated by Django 4.1.4 on 2023-01-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
