# Generated by Django 4.1.4 on 2023-01-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_discount_remove_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
